export const mockHarEntry = {
  $$id: 0,
  $$hidden: false,
  pageref: "page_1",
  startedDateTime: "2024-01-01T00:00:00.000Z",
  time: 123.45,
  request: {
    method: "GET",
    url: "https://example.com/api/test",
    httpVersion: "HTTP/1.1",
    headers: [{ name: "Content-Type", value: "application/json" }],
    headersSize: 120,
    queryString: [],
    cookies: [],
    bodySize: -1,
  },
  response: {
    status: 200,
    statusText: "OK",
    httpVersion: "HTTP/1.1",
    headers: [{ name: "Content-Type", value: "application/json" }],
    headersSize: 80,
    cookies: [],
    content: { size: 42, mimeType: "application/json", text: '{"ok":true}' },
    bodySize: 42,
    redirectURL: "",
  },
  cache: {},
  timings: { send: 1, wait: 100, receive: 22.45 },
  serverIPAddress: "93.184.216.34",
  _securityState: "secure",
  status: "200",
  statusText: "OK",
  method: "GET",
  url: "https://example.com/api/test",
};
